// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDKgrpfX92jBIxhLxEPuiuPQEqGoTwXaM',
    appId: '1:868490350353:web:34b836406058f7732a06b0',
    messagingSenderId: '868490350353',
    projectId: 'culturtap-otp-manager',
    authDomain: 'culturtap-otp-manager.firebaseapp.com',
    storageBucket: 'culturtap-otp-manager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxbHWlOxYdvtNs6wBqbHEsdiyd1c31qGM',
    appId: '1:868490350353:android:3950596392d575482a06b0',
    messagingSenderId: '868490350353',
    projectId: 'culturtap-otp-manager',
    storageBucket: 'culturtap-otp-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC82UqKuVegHxAGbgq0ozrpNaidrJH_pNc',
    appId: '1:868490350353:ios:47bf909ca6e5767e2a06b0',
    messagingSenderId: '868490350353',
    projectId: 'culturtap-otp-manager',
    storageBucket: 'culturtap-otp-manager.appspot.com',
    iosClientId:
        '868490350353-6rb0j6mj2qgk5a37eb43bha9g5t002sp.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC82UqKuVegHxAGbgq0ozrpNaidrJH_pNc',
    appId: '1:868490350353:ios:5cf74b83d136706c2a06b0',
    messagingSenderId: '868490350353',
    projectId: 'culturtap-otp-manager',
    storageBucket: 'culturtap-otp-manager.appspot.com',
    iosClientId:
        '868490350353-la0tboeu3kc5dhe12o09j6pj06p5qdq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFlutter.RunnerTests',
  );
}
